<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
$formUrl = $block->getUrl('product_question/question/submit');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
?>
<div class="product-feedback-form">
    <form id="feedback-form"
      method="post"
      action="<?= $formUrl ?>"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
        <?php echo $this->getBlockHtml('formkey')?>
        <input type="hidden" name="product_id" value="<?= $product->getId()?>" />
        <fieldset class="fieldset">
            <div class="field required">
                <label class="label" for="product-feedback-name"><?= __('Name') ?></label>
                <input class="input-text" name="name" type="text" id="product-feedback-name" data-validate="{required:true}"/>
            </div>
            <div class="field email required">
                <label class="label" for="product-feedback-name"><?= __('Email') ?></label>
                <input class="input-text" name="email" type="email" id="product-feedback-name" data-validate="{required:true, 'validate-email':true}"/>
            </div>
            <div class="field zipcode">
                <label class="label" for="product-feedback-zipcode"><?= __('Zipcode') ?></label>
                <input class="input-text" name="zip_code" type="text" id="product-feedback-zipcode"/>
            </div>
            <div class="field telephone required">
                <label class="label" for="product-feedback-phone"><?= __('Phone') ?></label>
                <input class="input-text" name="phone" type="text" id="product-feedback-phone" data-validate="{required:true}"/>
            </div>
            <div class="field required">
                <label class="label" for="product-feedback-comments"><?= __('Comments') ?></label>
                <textarea class="input-text" name="comments" rows="3" id="product-feedback-comments" data-validate="{required:true}"></textarea>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
