<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<div class="product-feedback-form">
    <form id="feedback-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="field requierd">
                <label class="label" for="product-feedback-name"><?= __('Name') ?></label>
                <input class="input-text" type="text" id="product-feedback-name" data-validate="{required:true}"/>
            </div>
            <div class="field email required">
                <label class="label" for="product-feedback-name"><?= __('Email') ?></label>
                <input class="input-text" type="email" id="product-feedback-name" data-validate="{required:true, 'validate-email':true}"/>
            </div>
            <div class="field zipcode">
                <label class="label" for="product-feedback-zipcode"><?= __('Zipcode') ?></label>
                <input class="input-text" type="text" id="product-feedback-zipcode"/>
            </div>
            <div class="field telephone required">
                <label class="label" for="product-feedback-phone"><?= __('Phone') ?></label>
                <input class="input-text" type="text" id="product-feedback-phone" data-validate="{required:true, 'validate-phone':true}"/>
            </div>
            <div class="field required">
                <label class="label" for="product-feedback-comments"><?= __('Comments') ?></label>
                <input class="input-text" type="text" id="product-feedback-comments" data-validate="{required:true}"/>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
